### PR TITLE
Continuing interrupted migration

### LINKED ISSUE #19: Permit continuing interrupted migration
Currently, there is no way to continue a migration process after e.g. a transaction failed. We should add an option to continue from a point where it failed before. For instance, we could return the last successfully stored key. That key could then be passed to continue from that point in the key/value mapping. Assuming the key/value map is always in the same order, that should be fine.

### PR DESCRIPTION
**Pull request by thecodingshrimp**
This PR will fix #19.

Tests can only be created when #30 is closed.

### CODE REVIEW

File: redeployContract.js [hunk 1]
```diff
@@ -251,51 +381,64 @@ const deployLargeContract = async (web3, target_address, contract_code, contract
...
     console.log('keys: ', keys);
     console.log('values: ', values);
+    if (keys.length < 1) return true;
+    let migrated = false;
     await initContract.methods.setValue(keys, values).send({
         from: target_address,
         gas: 4700000,
         gasPrice: '2000000000'
     })
         .on('error', function (error) {
```
Comment (thecodingshrimp) [inline redeployContract.js:448]: Checking for the error event is not enough to catch all errors.

We need to add the .catch() function as well to catch all errors and reliably write the interrupted-migration.json file for continuous migration.

**Review by thecodingshrimp — COMMENTED** [review]
in redeployContract.js we also need to add the .catch() function to all transactions sent to the blockchain in order to reliably write to interrupted-migration.json file when something was wrong while migrating.

This can be integrated, when #30 and #35 are closed

File: redeployContract.js [hunk 2]
```diff
@@ -118,28 +182,48 @@ const portContract = async (contract_address,
...
             console.log(`Replacing ${contract['contract_address'].substring(2).toLowerCase()} with ${contractAddress.substring(2).toLowerCase()}`);
             const regex = new RegExp(contract['contract_address'].substring(2).toLowerCase());
             contract_code = contract_code.replace(regex, contractAddress.substring(2).toLowerCase());
         }
     }
     
-
     // calculate how much the migration costs
-    let roughEstimate = Object.keys(storage).length * config.chain.deployingStorageCost + config.chain.gasBuffer;
+    let roughEstimate = Object.keys(storage).length < 1 ? 0 : Object.keys(storage).length * config.chain.deployingStorageCost + config.chain.gasBuffer;
```
Comment (informartin) [inline redeployContract.js]: Why is this required? If there are no keys, the rough estimate would end up with the gasBuffer, isn't this what is actually intended?

File: redeployContract.js [hunk 3]
```diff
@@ -151,91 +235,125 @@ const portContract = async (contract_address,
...
-            initContractAddress = receipt.contractAddress;
-            console.log('Init address: ', receipt.contractAddress); // contains the new contract address
-            console.log(`Actual gas used: ${receipt.gasUsed}`);
-            return receipt;
+    if (migrationResult.initAddress === undefined) {
+        console.log('Init bytecode: ', initCode);
+        initInstance = await initContract.deploy({ data: initCode }).send({
+            from: target_address,
+            gas: 4700000,
+            gasPrice: '2000000000'
```
Comment (informartin) [inline redeployContract.js]: The config values should be used here I guess.

File: redeployContract.js (hunk 1 above)
Comment (informartin) [reply redeployContract.js:448]: Was this resolved?

File: tests/test/simpleStorage.js [hunk 4]
```diff
@@ -1,11 +1,10 @@
 const { execSync } = require('child_process');
-const { assert } = require('console');
 const SimpleStorage = artifacts.require("SimpleStorage");
 const Web3 = require('web3');
 
 const source_dsl = 'http://localhost:8545';
 const target_dsl = 'http://localhost:8540';
-const target_address = '0x00ce0c25d2a45e2f22d4416606d928b8c088f8db';
+const continueMigrationFile = 'test/data/interruptedMigration.json';
```
Comment (informartin) [inline tests/test/simpleStorage.js:7]: Could we add another test here rather than replacing an old one? Or is the old one deprecated?

File: redeployContract.js (hunk 2 above)
Comment (thecodingshrimp) [reply redeployContract.js]: You are right.
I think this happened when I resolved the merge conflicts and accepted the wrong change.

File: redeployContract.js (hunk 3 above)
Comment (thecodingshrimp) [reply redeployContract.js]: Will do!

File: tests/test/simpleStorage.js (hunk 4 above)
Comment (thecodingshrimp) [reply tests/test/simpleStorage.js:7]: the old one is deprecated. I only set a continueMigrationFile so that the tests don't interfere with the normal workflow. I imagined the scenario where a user would try to migrate a contract, it fails and the output is written to interruptedMigration.json. The user changes the code and runs the tests for verification. Then, the interruptedMigration.json would be overwritten if I wouldn't have added this custom path for the interruptedMigration.

File: redeployContract.js (hunk 1 above)
Comment (thecodingshrimp) [reply redeployContract.js:448]: Yes

**Review by informartin — APPROVED** [review]
